version: "3.5"
services:
  api:
    build: .
    container_name: tvm.pns.api
    networks: 
      - tvm
    ports:
      - 3000:3000
    environment:
      PORT: 3000 
    #restart: always
networks:
  tvm:
